# -*- coding: utf-8 -*-
{
    'name': 'Sales - Customize Sales',
    'version': '1.2',
    'summary': 'Customize Sales',
    'author': 'Onnet Consulting',
    'sequence': 10,
    'website': 'on.net.vn',
    'description': """Customize Sale Order, create Po from SO, ...""",
    'category': 'Sales/Sales',
    'depends': ['sale_purchase',
                'sale_project',
                'sale_stock',
                'sale_management',
                'account',
                'report_xlsx',
                'soa_base'],
    'data': [
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/res_company_views.xml',
        # Report
        'report/layout_template.xml',
        'report/ir_action_report_template_sale_order.xml',
        'report/ir_action_report_template_account_invoice.xml',
        'report/ir_action_report.xml',
        'report/source_layout_template.xml',
        'report/ir_action_report_template_saleorder_rubio_pi.xml',
        'report/ir_action_report_template_invoice_rubio_ci.xml',
        'report/purchase_order_sourcing_report_xlsx.xml',
        'report/sale_order_sourcing_report_xlsx.xml',
        'report/account_invoice_sourcing_report_xlsx.xml',
        'report/sale_order_wood_report_xlsx.xml',
        'report/account_invoice_wood_report_xlsx.xml',
        'report/purchase_order_report_inherit.xml',
    ],
    'auto_install': True,
    'license': 'LGPL-3',
}
